### ISSUE TITLE
Can't customize this gem with `rails g migration`

### ISSUE THREAD

**Issue by huyngvu** [solidusio-contrib/solidus_related_products#16]
Hi,

I need to customize this gem to match with my project.

I i got error when trying this command `rails g migration`. The error is:

railties-5.0.0.1/lib/rails/engine/commands_tasks.rb:78:in `require': cannot load such file -- /home/huy/Developments/gems/solidus_related_products/lib/spree_related_products/engine (LoadError)
	from /home/huy/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/engine/commands_tasks.rb:78:in `load_generators'
	from /home/huy/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/engine/commands_tasks.rb:72:in `generate_or_destroy'
	from /home/huy/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/engine/commands_tasks.rb:44:in `generate'
	from /home/huy/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/engine/commands_tasks.rb:37:in `run_command!'
	from /home/huy/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/engine/commands.rb:14:in `<top (required)>'
	from bin/rails:7:in `require'
	from bin/rails:7:in `<main>'

Please help me about that.

Thanks,
Huy

**Comment by huyngvu** [comment]
I fixed it!
